### ISSUE TITLE
Recentish commit breaks MariaDB compatibility.

### ISSUE THREAD

**Issue by wispoffates** [AddstarMC/Prism-Bukkit#22] opened 2018-10-22 07:52 UTC
Not so much a bug as a heads up as the plugin does not advertise MariaDB support but until the commit it worked just fine.  

The problem is MariaDB does not have the ANY_VALUE Function/Aggregator as its a weird break to SQL OrderBy syntax and behavior.

This is the commit:
44eb961d317e14ac1fb409e3974ee4374c86e1a0

**Comment by Narimm** [comment] 2019-04-15 10:11
Yeah bloody mysql and non compatible sql 
I actually am working on this but the reality is the issue is that MariaDB doesn't use its own drivers...
It uses MYSQL drivers which DO support that SQL code.

**Comment by Narimm** [comment] 2019-05-31 12:21
Fixed in master

**Closed by Narimm** 2019-05-31 12:21 UTC
Labels: bug
