### ISSUE TITLE
player_head BlockBreakEvent failing

### ISSUE THREAD

**Issue by MiniWorks18** [AddstarMC/Prism-Bukkit#26] opened 2019-01-20 11:45 UTC
When I break a player_head, the event fails to pass through Prism, it doesn't log the event and throws this stack trace. I am unaware of any other blocks causing this issue.

> 2019-01-20 22:35:30 [Server thread/ERROR]: Could not pass event BlockBreakEvent to Prism v2.1.0-27
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-504]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-504]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-504]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-504]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299) ~[patched_1.13.2.jar:git-Paper-504]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:226) ~[patched_1.13.2.jar:git-Paper-504]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1299) ~[patched_1.13.2.jar:git-Paper-504]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-504]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-504]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-504]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-504]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-504]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-504]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-504]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-504]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassCastException

**Comment by k-jiang** [comment] 2019-09-17 00:52
Confirmed in Paper 1.14.4. Probably due to bukkit api changes?
Tested with 45a8f07
```
[08:45:16 ERROR]: Could not pass event BlockBreakEvent to Prism v2.1.1-SNAPSHOT-${env.BUILD_NUMBER}
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_14_R1.block.impl.CraftSkullPlayer incompatible with org.bukkit.block.data.Directional
        at me.botsko.prism.actions.BlockAction.setBlock(BlockAction.java:76) ~[?:?]
        at me.botsko.prism.actions.BlockAction.setBlock(BlockAction.java:49) ~[?:?]
        at me.botsko.prism.actionlibs.ActionFactory.createBlock(ActionFactory.java:65) ~[?:?]
        at me.botsko.prism.listeners.PrismBlockEvents.onBlockBreak(PrismBlockEvents.java:216) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor786.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-192]
        at org.bukkit.plugin.EventExecutor$$Lambda$3015.0000000075701030.execute(Unknown Source) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-192]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-192]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:303) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:262) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:236) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1307) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$4562.00000000DC1AB4A0.run(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1135) ~[patched_1.14.4.jar:git-Paper-192]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-192]
        at java.lang.Thread.run(Thread.java:819) [?:1.8.0_212]
```

**Comment by addstar** [comment] 2020-01-29 22:04
Fixed in the latest version

**Closed by addstar** 2020-01-29 22:04 UTC
