### ISSUE TITLE
[BUG] Document required action

### ISSUE THREAD

**Issue by Katrix** [AddstarMC/Prism-Bukkit#227] opened 2020-10-21 08:56 UTC
**Describe the bug**
On the wiki page for the parameters, it says that the default for `a:` is all, with no mention of `prism.parameters.action-filter-bypass`. Trying that permission doesn't actually work either though, it seems like you need to deny the permission `prism.parameters.action.required` currently.

**To Reproduce**
Try to execute a lookup without the permission, and without an action.

**Expected behavior**
A better error message, or documented behavior.

**Server (please complete the following information):**
  - Prism Version: 2.1.7
  - Server Type: Paper
  - Server Version: 1.16.3

**Comment by Narimm** [comment] 2020-10-21 11:27
Not a bug and already fixed in dev version anyway

**Closed as completed by Narimm** 2020-10-21 11:27 UTC
Labels: invalid
