### ISSUE TITLE
[BUG] Updating prism schema v7 to v8: Duplicate key name 'player'

### ISSUE THREAD

**Issue by viveleroi** [AddstarMC/Prism-Bukkit#264] opened 2021-05-14 19:12 UTC
**Describe the bug**

Ran prism 2.1.7.6 on our dev server, where 2.1.6 was the last version.

```
[Prism] Updating prism schema v7 to v8. This make take a while.
[12:06:45] [Craft Scheduler Thread - 15/ERROR]: [Prism] Database connection error: Duplicate key name 'player'
[12:06:45] [Craft Scheduler Thread - 15/WARN]: java.sql.SQLSyntaxErrorException: Duplicate key name 'player'
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1333)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2106)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1243)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at com.botsko.prism.libs.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at com.botsko.prism.libs.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at me.botsko.prism.database.sql.SqlPrismDataSourceUpdater.v7_to_v8(SqlPrismDataSourceUpdater.java:106)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at me.botsko.prism.Updater.applyUpdates(Updater.java:53)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at me.botsko.prism.Prism.lambda$onEnable$5(Prism.java:381)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[12:06:45] [Craft Scheduler Thread - 15/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**To Reproduce**
Not sure. Last used prism 2.1.6, tried updating with 2.1.7.6 for the first time.

**Expected behavior**
No errors.

**Server (please complete the following information):**
  - Prism Version: 2.1.7.6
  - Server Type: Paper
  - Server Version: 1.16.5

**Comment by Narimm** [comment] 2021-08-15 23:05
Closed as this is a duplicate of #235

**Closed as completed by Narimm** 2021-08-15 23:05 UTC
Labels: duplicate
